### ISSUE TITLE
Where are the lasers?!?

### ISSUE THREAD

**Issue by ckskate** [wjwalcher/wjwalcher.github.io#1]
I'd give this site about a 69/420. As a true Rick and Morty fan who understands all the references, I was quite a bit dismayed to find that this website didn't stimulate my quite substantial intellect in a meaningful way. *sighs* perhaps that's fate us gents with IQs >160 must resign ourselves to.

I'd also like everyone to know that I can understand some of the words in my favorite animes without the subtitles. *tips fedora*

**Comment by wjwalcher** [comment]
I’ll make sure to address this in the next update

**Comment by dukeeagle** [comment]
Same
